#ifndef __CONSTANTS_H__

#define __CONSTANTS_H__

#define FILE_NAME_SIZE 50

#define OK 0
#define MEMORY_ALLOCATION_ERROR -1
#define FILE_OPEN_ERROR -2
#define MATRIX_FILL_PARAMETR_ERROR -3
#define MATRIX_FILL_ELEMENT_ERROR -4
#define FILENAME_FILL_ERROR -5
#define MENU_NUMBER_ERROR -6
#define FILE_MISSING_ERROR -7

#endif // __CONSTANTS_H__
